name: Hello Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 1 minute
  workflow_dispatch:       # Also allows manual run

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile HelloWorld.java
        run: javac HelloWorld.java

      - name: Run HelloWorld
        run: java HelloWorld
